#!/bin/sh
printf "Doing Wizard Things.......\n"
printf "                  .       \n"
printf "                          \n"
printf "                   .      \n"
printf "         /^\     .        \n"
printf "    /\   \?/              \n"
printf "   /__\   I      O  o     \n"
printf "  /|..|\  I     .         \n"
printf "  \] ?[/  I               \n"
printf "  /l/\j\  (3    .  O      \n"
printf " /. ~~ ,\/I          .    \n"
printf " \ \\__j^\/I       o       \n"
printf "  \\\\3--v}  I     o   .     \n"
printf "  |    |  I   _________   \n"
printf "  |    |  I c(        ')o \n"
printf "  |    l  I   \.     ,/   \n"
printf "_/j  L l\_!  _//^---^ \_  \n"
